2. Print messages
Tell your friends what you learned in this pathway.

Can you write a main() function that prints these messages on four separate lines?

Use the val keyword when the value doesn't change. 
Use the var keyword when the value can change.
When you define a function, you define the parameters that can be passed to it. 
When you call a function, you pass arguments for the parameters.

#code
fun main() {
    println("Use the val keyword when the value doesn't change.\n") 
	println("Use the var keyword when the value can change.\n")
	println("When you define a function, you define the parameters that can be passed to it.\n") 
	println("When you call a function, you pass arguments for the parameters.")
}
